version: '3.6'
services:
  # Mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
